# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/

language: cpp

env:
  global:
  - CATCH2_REPO_URL=https://github.com/catchorg/Catch2.git
  - CATCH2_BRANCH=v2.13.2
  - CATCH2_DIRECTORY=${HOME}/Catch2
  - TCHECKER_BUILD_TYPE=Debug

before_cache:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -mindepth 1 -delete; fi

cache:
  directories:
  - ${HOME}/Library/Caches/Homebrew
  - /usr/local/Homebrew
  - ${CATCH2_DIRECTORY}

dist: focal

jobs:
  include:
  - name : "linux-gcc-int64-covreach"
    os: linux
    compiler: gcc
    env: CONFNAME="covreach:int64:memcheck"
  - name : "linux-gcc-covreach"
    os: linux
    compiler: gcc
    env: CONFNAME="covreach:int32:memcheck"
  - name : "linux-gcc-explore"
    os: linux
    compiler: gcc
    env: CONFNAME="explore:int32:memcheck"
  - name : "linux-gcc-simple_tests+memcheck"
    os: linux
    compiler: gcc
    env: CONFNAME="smallest:int32:memcheck"
  - name : "linux-gcc-int16-simple_tests+memcheck"
    os: linux
    compiler: gcc
    env: CONFNAME="smallest:int16:memcheck"
  - name : "linux-gcc-int64-simple_tests+memcheck"
    os: linux
    compiler: gcc
    env: CONFNAME="smallest:int64:memcheck"

  - name : "linux-clang-simple_tests+memcheck"
    os: linux
    compiler: clang
    env: CONFNAME="smallest:int32:memcheck"

  - name : "macos-gcc-simple_tests"
    os: osx
    osx_image: xcode12.2
    compiler: gcc
    env: CONFNAME="smallest:int32:no-memcheck"
  - name : "macos-gcc-int64-simple_tests"
    os: osx
    osx_image: xcode12.2
    compiler: gcc
    env: CONFNAME="smallest:int64:no-memcheck"
  - name : "macos-clang-simple_tests"
    os: osx
    osx_image: xcode12.2
    compiler: clang
    env: CONFNAME="smallest:int32:no-memcheck"

install:
- . ./ci-scripts/setenv-common.sh
- ./ci-scripts/install-${TRAVIS_OS_NAME}.sh
- . ./ci-scripts/setenv-${TRAVIS_OS_NAME}.sh
- ./ci-scripts/show-config.sh

script:
- ./ci-scripts/build.sh
- ./ci-scripts/test.sh

addons:
  apt:
    packages:
    - libboost-all-dev
    - valgrind
    update: true
  homebrew:
    packages:
    - boost
    - bison@3.7
    update: true

notifications:
  email: true

